### ISSUE TITLE
Patch for el7

### ISSUE THREAD

**Issue by marhsu** [espebra/el6-from-tmpfs-patch#1]
Do you have a patch for el7?

thanks
Martin Hsu

**Comment by espebra** [comment]
Hi Martin,

I haven't had the time to do that, unfortunately. I'll try to get the time to do it soon, and then I'll update this issue to let you know.

**Comment by marhsu** [comment]
Any chance to work on this yet?

Thanks
Martin Hsu

**Comment by espebra** [comment]
Hi. I've ordered some hw to use for this, so I expect to have the patch in place in a couple of weeks.

**Comment by marhsu** [comment]
Hi Espen,

Any progress on this?

Thanks
Martin Hsu

**Comment by espebra** [comment]
Hi,

Thank you for polling. I've had a look at it, but there are unfortunately some challenges i EL7 that are not in EL6. I will need to dig a bit to figure out what's wrong.

**Comment by marhsu** [comment]
Hi Espen,
Thank you for helping out on this, I really appreciate it

**Comment by espebra** [comment]
I'll close this now. The hardware is in place, but I just don't have the time to prioritise this unfortunately.

**Comment by espebra** [comment]
Hi @marhsu 

I finally got around to look into this again, and wrote a blog post about it at http://www.espenbraastad.no/. Hopefully you can use it :)
